### ISSUE TITLE
Inconsistent frequency in the MeasYaps headers

### ISSUE THREAD

**Issue by darrencl** [TRIImaging/MagneticResonanceSignals.jl#4]
I found out that in very few occasion, the frequency in MeasYaps and the rest (including `ASCCONV` in Phoenix header are different and the frequency in the rest are consistent.

For instance, in these data:
```
sTXSPEC.asNucleusInfo[0].lFrequency	 = 	123255367 # MeasYaps
sTXSPEC.asNucleusInfo[0].lFrequency	 = 	123254822 # Phoenix
... #
<ParamLong."lFrequency">
 {
   123254822
 }
```
Below snippet proving MeasYaps is different from the rest, in the few occasion discussed above. 
```julia
# Phoenix
julia> for line in split(header_sections["Phoenix"], "\n")
           if occursin("lFrequency", line)
               print(line)
           end
       end
sTXSPEC.asNucleusInfo[0].lFrequency	 = 	123254822

# MeasYaps
julia> for line in split(header_sections["MeasYaps"], "\n")
           if occursin("lFrequency", line)
               print(line)
           end
       end
sTXSPEC.asNucleusInfo[0].lFrequency	 = 	123255367

# Dicom
julia> for line in split(header_sections["Dicom"], "\n")
           if occursin("lFrequency", line)
               print(line)
           end
       end
      <ParamLong."lFrequency">  { 123254822  }

# Meas
julia> let
           counter = 0
           for line in split(header_sections["Meas"], "\n")
               if occursin("lFrequency", line) 
                   counter = 3
               end
               if counter > 0
                   println(line)
               end
               counter-=1
           end
       end
            <ParamLong."lFrequency"> 
            {
            }
              <ParamLong."lFrequency"> 
              {
              }
      <ParamLong."lFrequency"> 
      {
        123254822 

```
Therefore, I am proposing to change the following to use the `ASCCONV` in `Phoenix` instead of `MeasYaps`
https://github.com/TRIImaging/MagneticResonanceSignals.jl/blob/1d81be222e247e2b3af030d07924965ec52cb8bb/src/io_twix.jl#L336

@c42f Any thoughts?

**Comment by c42f** [comment]
It's a bit hard to guess why these might be different without fiddling with the measurement protocol on an actual scanner.

One guess could be that it happens when the adjustments are invalidated by the operator after the initial setup and the central frequency is measured again. Thus resulting in two entries, in which case you should take the second? But this is just a wild guess.

The difference is also rather small here, so I don't think this should effect things much either way — It'll only cause a very slight and insignificant rescaling of the ppm scale, I think?

**Comment by bennyrowland** [comment]
Completely agree about the challenges of figuring out why this occurs, I don't know enough about the purpose of each file in the Twix header to tell at what point they all get populated. The difference in frequency is 545Hz, or about 4.4ppm. Therefore I would be surprised if there was such a shift in the field after initial setup, although I suppose it might happen if there was a reshim. @darrencl has pointed out a similar shift in the openmrslab/suspect test data, but there it is only 8Hz which really is a tiny shift.

@c42f is right to say that the only consequence is an undetectable rescaling of the ppm axis, as long as the frequency used was the right one. If the receiver frequency has been changed manually from the correct one (centred on the water peak) then there will also be a shift of the ppm scale, as 4.7ppm will no longer correspond to 0Hz, and this could also produce chemical shift localisation issues etc. I think that this is unlikely to be the case here though, I am sure you would notice a shift that big in the data.

**Comment by c42f** [comment]
> although I suppose it might happen if there was a reshim

Several of the radiographers on the project did tend to manually adjust the shimming regularly and sometimes invalidate all adjustments and begin from scratch. So it's a possibility I guess. Weird though.
